name: Deploy Static Site

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.J5-QkmRXMK9seGHcHFXR6Iko0dtY54-HY9l0OVkw }}
          accountId: ${{ secrets.9859ea73ac4db59e348c1cf03420dfbd }}
          projectName: "bioxmind"
          directory: "."
